# 权限管理API测试

@baseUrl = http://localhost:8080

@platformAdminToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgxMjM0NTY3OCIsImlhdCI6MTc2NDY3MDY5OSwiZXhwIjoxNzY2NTM0Njk5fQ.lk99LWqbRVgLVszrSTowyVqAjYH91voDzf8O81MfSuq35KGYsuCb1uUOaqXo3zvJ

# 68e71bea-421c-42b6-b796-1a480190afdd机构，管理员
@supervisorId = c4d9798f-4701-4ea1-b49d-218b84235432
@institutionSupervisorToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgwMDAwMDEwMCIsImlhdCI6MTc2NDgxOTE4NCwiZXhwIjoxNzY2NjgzMTg0fQ.YS4WV4wRdC_BNVT_6q5_tk5oy_yKV0bM4MJFTlnyOch9lXHdjbjl1A-SoNqfdXNb

# 68e71bea-421c-42b6-b796-1a480190afdd机构，数据集上传员7c34890d-e50b-44e1-991a-fbad1842fd25
@providerId = 7c34890d-e50b-44e1-991a-fbad1842fd25
@datasetUploaderToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgwMDAwMDEwMSIsImlhdCI6MTc2NDgxOTI0MiwiZXhwIjoxNzY2NjgzMjQyfQ.Lm1gEVO0YJJwPMvyb2ejd5A-fD2cpLMIyJJfsAYpAg8oB6VCK0Dlb10o5_R3nC8u

# 9664a7c9-e337-48d6-a55e-547c285f4ea7机构，管理员99ec84d8-9ccb-4a53-be97-4f385cb2d044
@personToken = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgwMDAwMDIwMSIsImlhdCI6MTc2NDc1MjUyNywiZXhwIjoxNzY2NjE2NTI3fQ.dPuF4svGddDkbg5_c9ZXs-qLJdXHSTa76D2OWhEHV2WijYI9QNg1VRrbFSUaVmLN

# 没有权限的用户的令牌，机构9664a7c9-e337-48d6-a55e-547c285f4ea7，用户73ae0020-822c-4296-ad0e-1436b43b8875
@noPermissionUserToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgwMDEzODAwMCIsImlhdCI6MTc2NTU1MzAxMSwiZXhwIjoxNzY3NDE3MDExfQ.CgYCrGEm-PmQWwdEXIBNVpb2Sv1gN9F3irgtp5Ooov5oYyOyOfv8NTaxIX3bjTk8


### 获取当前用户（自己）的权限列表 - 平台管理员
GET {{baseUrl}}/api/users/authorities
Authorization: Bearer {{datasetUploaderToken}}

### 获取所有权限列表 - 平台管理员
GET {{baseUrl}}/api/manage/authorities
Authorization: Bearer {{platformAdminToken}}

### 获取指定用户的权限列表 - 平台管理员
GET {{baseUrl}}/api/manage/authorities/fc46ed5a-90f2-4edb-912a-4a1f5c0a21f0
Authorization: Bearer {{platformAdminToken}}

### 获取所有权限列表 - 机构管理员
GET {{baseUrl}}/api/manage/authorities
Authorization: Bearer {{personToken}}

### 获取指定用户的权限列表 - 机构管理员（同一机构）
GET {{baseUrl}}/api/manage/authorities/fc46ed5a-90f2-4edb-912a-4a1f5c0a21f0
Authorization: Bearer {{institutionSupervisorToken}}

### 更新用户权限 - 平台管理员操作
PUT {{baseUrl}}/api/manage/authorities
Authorization: Bearer {{platformAdminToken}}
Content-Type: application/json

{
  "userId": "fc46ed5a-90f2-4edb-912a-4a1f5c0a21f0",
  "authorities": ["PLATFORM_ADMIN","INSTITUTION_SUPERVISOR", "DATASET_UPLOADER"]
}

### 更新用户权限 - 机构管理员操作（不包含平台管理员权限）
PUT {{baseUrl}}/api/manage/authorities
Authorization: Bearer {{institutionSupervisorToken}}
Content-Type: application/json

{
  "userId": "fc46ed5a-90f2-4edb-912a-4a1f5c0a21f0",
  "authorities": ["DATASET_UPLOADER"]
}

### 更新用户权限 - 机构管理员尝试添加平台管理员权限（应该被拒绝，且不能修改平台管理员的权限）
PUT {{baseUrl}}/api/manage/authorities
Authorization: Bearer {{platformAdminToken}}
Content-Type: application/json

{
  "userId": "fc46ed5a-90f2-4edb-912a-4a1f5c0a21f0",
  "authorities": ["PLATFORM_ADMIN", "DATASET_UPLOADER"]
}