@institutionId=68e71bea-421c-42b6-b796-1a480190afdd

@auth_token = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgwMDEzODAwMiIsImlhdCI6MTc2NDY3MTIzNCwiZXhwIjoxNzY2NTM1MjM0fQ.SK-ixBne4YuvdQtSpLTin2niXS8z2MV_L700Pck9G2bs_-EWLixWPd2Vsbk35tAj

@auth_token_platform_admin = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgxMjM0NTY3OCIsImlhdCI6MTc2NDY3MDY5OSwiZXhwIjoxNzY2NTM0Njk5fQ.lk99LWqbRVgLVszrSTowyVqAjYH91voDzf8O81MfSuq35KGYsuCb1uUOaqXo3zvJ

@auth_token_institution_admin = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgwMDAwMDEwMCIsImlhdCI6MTc2NDcyOTg5MCwiZXhwIjoxNzY2NTkzODkwfQ.aBIvN0a1KZ1_hzijW7LmupYnvKm7yMEWlobMOtQj_w1nHXm-z0xgGJPXTQWzlBgm


### 获取所有机构（公开接口，只返回已验证的机构）
GET http://localhost:8080/api/institutions
Accept: application/json

### 根据ID获取特定已验证机构（公开接口）
GET http://localhost:8080/api/institutions/{{institutionId}}
Accept: application/json

### 平台管理员登录（用于获取token）
# @name login_platform_admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "phone": "13800000001",
  "password": "Admin123456",
  "loginType": "PASSWORD"
}

### 机构管理员登录（用于获取token）
# @name login_institution_admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "phone": "13800000100",
  "password": "Institution123456",
  "loginType": "PASSWORD"
}

### 平台管理员获取所有机构列表
GET http://localhost:8080/api/manage/institutions
Authorization: Bearer {{auth_token_platform_admin}}
Accept: application/json

### 平台管理员根据ID获取特定机构
GET http://localhost:8080/api/manage/institutions/{{institutionId}}
Authorization: Bearer {{auth_token_platform_admin}}
Accept: application/json

### 平台管理员创建新机构
POST http://localhost:8080/api/manage/institutions
Authorization: Bearer {{auth_token_platform_admin}}
Content-Type: application/json

{
  "fullName": "东院",
  "shortName": "院",
  "type": "hospital",
  "contactPerson": "东医生",
  "contactIdType": "national_id",
  "contactIdNumber": "110101199003077532",
  "contactPhone": "13800000003",
  "contactEmail": "contact@hospital.example.com"
}

### 平台管理员更新机构信息
PUT http://localhost:8080/api/manage/institutions/{{institutionId}}
Authorization: Bearer {{auth_token_platform_admin}}
Content-Type: application/json

{
  "fullName": "北京大学第一医院（更新）",
  "shortName": "北大一院",
  "type": "hospital",
  "contactPerson": "李医生",
  "contactIdType": "national_id",
  "contactIdNumber": "110101199003077532",
  "contactPhone": "13800000004",
  "contactEmail": "contact@hospital.example.com"
}

### 机构管理员获取自己所属机构的信息
GET http://localhost:8080/api/manage/institutions/own
Authorization: Bearer {{auth_token_institution_admin}}
Accept: application/json

### 机构管理员更新自己所属机构的信息
PUT http://localhost:8080/api/manage/institutions/own
Authorization: Bearer {{auth_token_institution_admin}}
Content-Type: application/json

{
  "fullName": "清华大学附属医院（更新）",
  "shortName": "清华附院",
  "type": "hospital",
  "contactPerson": "王医生j",
  "contactIdType": "national_id",
  "contactIdNumber": "110101199003077533",
  "contactPhone": "13800000005",
  "contactEmail": "contact@tsinghua-hospital.example.com"
}

### 平台管理员删除机构
DELETE http://localhost:8080/api/manage/institutions/{{institutionId}}
Authorization: Bearer {{auth_token_platform_admin}}

### 平台管理员添加用户，并设置其机构为，并添加机构管理员的权限
POST http://localhost:8080/api/manage/users
Authorization: Bearer {{auth_token_platform_admin}}
Content-Type: application/json

{
  "phone": "13800000101",
  "username": "new_institution_admin",
  "realName": "新机构管理员",
  "email": "newadmin@example.com",
  "password": "InstitutionAdmin123",
  "institutionId": "{{institutionId}}"
}

### 平台管理员验证通过机构
PATCH http://localhost:8080/api/manage/institutions/{{institutionId}}/verify
Authorization: Bearer {{auth_token_platform_admin}}
Accept: application/json

### 机构管理员验证通过自己所属的机构
PATCH http://localhost:8080/api/manage/institutions/{{institutionId}}/verify
Authorization: Bearer {{auth_token_institution_admin}}
Accept: application/json