@phone = 13800000101
@phone1 = 13812345678
@admin_token = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgxMjM0NTY3OCIsImlhdCI6MTc2NDY3MDY5OSwiZXhwIjoxNzY2NTM0Njk5fQ.lk99LWqbRVgLVszrSTowyVqAjYH91voDzf8O81MfSuq35KGYsuCb1uUOaqXo3zvJ

@institution_token = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgwMDAwMDEwMCIsImlhdCI6MTc2NDgxOTE4NCwiZXhwIjoxNzY2NjgzMTg0fQ.YS4WV4wRdC_BNVT_6q5_tk5oy_yKV0bM4MJFTlnyOch9lXHdjbjl1A-SoNqfdXNb

@auth_token = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxMzgwMDEzODAwMiIsImlhdCI6MTc2NDY3MTIzNCwiZXhwIjoxNzY2NTM1MjM0fQ.SK-ixBne4YuvdQtSpLTin2niXS8z2MV_L700Pck9G2bs_-EWLixWPd2Vsbk35tAj

### 发送注册验证码
POST http://localhost:8080/api/auth/send-verification-code?phone={{phone}}&businessType=REGISTER

### 注册新用户
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "phone": {{phone}},
  "verificationCode": "679066",
  "username": "testuser",
  "realName": "测试用户",
  "email": "test@example.com",
  "password": "Test123456"
}

### 发送登录验证码
POST http://localhost:8080/api/auth/send-verification-code?phone={{phone}}&businessType=LOGIN

### 验证码登录
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "phone": {{phone}},
  "verificationCode": "193689",
  "loginType": "VERIFICATION_CODE"
}

### 密码登录
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "phone": {{phone}},
  "password": "Test123456",
  "loginType": "PASSWORD"
}

### 获取当前用户信息
GET http://localhost:8080/api/users/profile
Authorization: Bearer {{auth_token}}

### 根据用户ID获取用户信息（需要在user_authority添加管理员权限记录）
GET http://localhost:8080/api/users/73ae0020-822c-4296-ad0e-1436b43b8875
Authorization: Bearer {{admin_token}}

### 登出
POST http://localhost:8080/api/auth/logout
Authorization: Bearer {{auth_token}}

