### 发送验证码
POST http://localhost:8080/api/users/send-verification-code?phoneNumber=13800138000&businessType=REGISTER
Content-Type: application/json

### 用户注册
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "phoneNumber": "13800138000",
  "verificationCode": "010853",
  "username": "testuser",
  "realName": "测试用户",
  "email": "test@example.com",
  "password": "password123"
}